#@ load("@ytt:data", "data")
---
#cloud-config

# This is the user-data configuration file for cloud-init. By default this sets
# 
# up an initial user called "ubuntu" with password "ubuntu", which must be
# changed at first login. However, many additional actions can be initiated on
# first boot from this file. The cloud-init documentation has more details:
#
# https://cloudinit.readthedocs.io/
#
# Some additional examples are provided in comments below the default
# configuration.
fqdn: #@ "jumpbox.{}".format(data.values.domain)
ssh_authorized_keys: #@ data.values.ssh.authorized_keys

## don't require a password change since we just set it
chpasswd:
  expire: false

## add package repositories
apt:
  preserve_sources_list: true
  sources:
    microsoft:
      source: #@ data.values.microsoft.repository 
      key: #@ data.values.microsoft.pgp_key
   tailscale:
      source: #@ data.values.tailscale.repository
      key: #@ data.values.tailscale.pgp_key

## Update apt database and upgrade packages on first boot
package_update: true
package_upgrade: true

## Install additional packages on first boot
packages:
- open-vm-tools
- ca-certificates
- curl
- zsh
- neovim
- mssql-server
- powershell
- tailscale

groups:
- ssher

write_files:
- path: /etc/ssh/ssh_host_ed25519_key
  content: #@ data.values.ssh_host_key.private
  permissions: '0644'
  owner: root:root
- path: /etc/ssh/ssh_host_ed25519_key.pub
  content: #@ data.values.ssh_host_key.public
  permissions: '0644'
  owner: root:root
- path: /etc/ssh/sshd_config.d/01-hardening.conf
  content: |
    # enable eed25519 key
    HostKey /etc/ssh/ssh_host_ed25519_key

    # restrict supported key exchange, cipher, and MAC algorithms
    KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256
    Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
    MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
    HostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-512,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com

    # restrict authentication mechanism
    PasswordAuthentication yes
    ChallengeResponseAuthentication no
    PubkeyAuthentication yes
  permissions: '0644'
  owner: root:root
- path: /etc/ssh/sshd_config.d/88-gpg-forwarding.conf
  content: |
    # Enables automatic removal of stale sockets to support GPG forwarding
    StreamLocalBindUnlink yes
  permissions: '0644'
  owner: root:root
- path: /etc/ssh/ssh_config.d/01-hardening.conf
  content: |
    Host github.com
      KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
    Host *
      # restrict supported key exchange, cipher, and MAC algorithms
      KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256
      Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
      MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
      HostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-512,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com

      # restrict authentication mechanism
      PasswordAuthentication no
      ChallengeResponseAuthentication no
      PubkeyAuthentication yes
  permissions: '0644'
  owner: root:root

runcmd:
- ACCEPT_EULA=y msodbcsql17 mssql-tools unixodbc-dev
- rm /etc/ssh/ssh_host_dsa_key* /etc/ssh/ssh_host_ecdsa_key* /etc/ssh/ssh_host_rsa_key* 
- awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.safe
- mv /etc/ssh/moduli.safe /etc/ssh/moduli
- usermod -a -G ssher ubuntu 
- echo "# limit who can use SSH\nAllowGroups ssher" > /etc/ssh/ssh_config.d/02-limit-to-ssher.conf
